services:
  checker:
    build:
      target: production
    environment:
      INTERVAL_MINUTES: ${INTERVAL_MINUTES}
      NOTIFICATION_TIMEOUT_MINUTES: ${NOTIFICATION_TIMEOUT_MINUTES}
      USERNAMES: ${USERNAMES}
      DISCORD_USER_IDS: ${DISCORD_USER_IDS}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL}
